# Generated by Django 4.0.5 on 2022-06-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcapteur', models.CharField(max_length=100)),
                ('emplacement', models.CharField(default='Emplacement à définir', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcollecte.capteurs')),
            ],
        ),
    ]
